name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown Accessibility
        uses: sam9111/markdown-accessibility-helper@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
