name: My Workflow

on:
  push:
    paths:
      - "**.md"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Accessibility
        uses: sam9111/markdown-accessibility-helper@v1.0.1
